<?php
require_once './modelos/ModeloPropiedades.phtml';
require_once './vistas/VistaPropiedades.phtml';

class ControladorPropiedades {
    private $modelo;
    private $vista;

    public function __construct() {
        $this->modelo = new ModeloPropiedades();
        $this->vista = new VistaPropiedades(); 
    }

    public function mostrarPropiedades() {
        $propiedades = $this->modelo->obtenerPropiedades();
        $this->vista->mostrarPropiedades($propiedades);
    }

   /* public function mostrarPropiedades($id_propietario){//de uno especifico
        $propiedades = $this->modelo->obtenerPropiedadesPorPropietario($id_propietario);
        $propietario = $this->modelo->obtenerPropietarioPorId($id_propietario);
        $this->vista->mostrarPropiedadesPorPropietario($propietario, $propiedades);
    }*/

    //Form agregar propiedad
    public function agregarPropiedad() {
        if($_SERVER['REQUEST_METHOD'] === 'POST') {
            $id_propietario = $_POST['id_propietario_fk'];
            $tipo_propiedad = $_POST['tipo_propiedad'];
            $ubicacion= $_POST['ubicacion'];
            $habitaciones = $_POST['habitaciones'];
            $metros_cuadrados = $_POST['metros_cuadrados'];

            $this->modelo->agregarPropiedad($id_propietario, $tipo_propiedad,$ubicacion,$habitaciones,$metros_cuadrados);
            header('Location: ' . BASE_URL . 'propiedades');
            exit();
        } else {
            $this->vista->formularioAgregarPropiedad();
        }
    }

    //Form editar propiedad
    public function mostrarForumularioEditarPropiedad($id_propiedad) {
        $propiedad = $this->modelo->obtenerPropiedadPorId($id_propiedad);
        if($propiedad) {
            $this->vista->forumularioEditarPropiedad($propiedad);
        } else {
            $this->vista->mostrarErrorEditar("No se encontro propiedad con el ID: " . $id_propiedad);
        }
    }


    //Editar propiedad
    public function editarPropidad($id_propiedad) {
        if($_SERVER['REQUEST_METHOD'] === 'POST') {
            $id_propietario = $_POST['id_propietario_fk'];
            $tipo_propiedad = $_POST['tipo_propiedad'];
            $ubicacion= $_POST['ubicacion'];
            $habitaciones = $_POST['habitaciones'];
            $metros_cuadrados = $_POST['metros_cuadrados'];
            $this->modelo->editarPropiedad($id_propiedad, $id_propietario, $tipo_propiedad, $ubicacion, $habitaciones, $metros_cuadrados);
            header('Location: ' . BASE_URL . 'propiedades');
            exit();
        }
    }


    public function eliminarPropiedad() {
        if ($_SERVER['REQUEST_METHOD'] === 'POST') {
            $id_propiedad = $_POST['id_propiedad'];
            $this->modelo->eliminarPropiedad($id_propiedad);
            header('Location:' . BASE_URL . 'propiedad');
            exit();
            } else {
                $this->vista->mostrarErrorEliminar();
            }
        }
    }
