<?php require 'templates/header.phtml' ?>

<form action=" " method="" class="">
      <div class="mb-3">
        <label for="id_propietario_fk">Propietario</label>
        <select id="id_propietario_fk" name="id_propietario_fk" class="form-control" required>
            <?php foreach ($propietarios as $propietario): ?>
                <option value="<?= $propietario->id ?>"
                    <?= $propietario->id == $propiedad->id_propietario_fk ? 'selected' : '' ?>>
                    <?= htmlspecialchars($propietario->nombre) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="mb-3">
        <label for="tipo_propiedad">Tipo de propiedad</label>
        <input type="text" id="tipo_propiedad" name="tipo_propiedad" class="form-control"
               value="<?= htmlspecialchars($propiedad->tipo_propiedad) ?>" required>
    </div>

    <div class="mb-3">
        <label for="ubicacion">Ubicación</label>
        <input type="text" id="ubicacion" name="ubicacion" class="form-control"
               value="<?= htmlspecialchars($propiedad->ubicacion) ?>" required>
    </div>

    <div class="mb-3">
        <label for="habitaciones">Cantidad de habitaciones</label>
        <input type="number" id="habitaciones" name="habitaciones" class="form-control"
               value="<?= $propiedad->habitaciones ?>" required>
    </div>

    <div class="mb-3">
        <label for="metros_cuadrados">Metros cuadrados</label>
        <input type="number" id="metros_cuadrados" name="metros_cuadrados" class="form-control"
               value="<?= $propiedad->metros_cuadrados ?>" required>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Editar</button>
    
    <a href="<?= BASE_URL ?>propiedades" class="btn btn-secondary">Cancelar</a>

</form>

<?php require 'templates/footer.phtml' ?>