<?php require 'templates/header.phtml' ?>

<div class="agregar-container">
    <h2 style="font-family: 'Montserrat', Arial, sans-serif; color: #d32f2f; margin-bottom: 18px;">Agregar una propiedad</h2>
    <form action="<?= BASE_URL ?>agregarPropiedad" method="POST" class="agregar-form">
        <div class="form-group">
            <label for="id_propietario_fk">Propietario</label>
            <select id="id_propietario_fk" name="id_propietario_fk" >
                <option value="">Seleccione un propietario</option>
                <?php foreach($propietarios as $propietario): ?>
                    <option value="<?= $propietario->id_propietario ?>">
                        <?= htmlspecialchars($propietario->nombre) ?>
                    </option>
    <?php endforeach; ?>
</select>
        </div>
        <div class="form-group">
            <label for="tipo_propiedad">Tipo de propiedad</label>
            <input type="text" id="tipo_propiedad" name="tipo_propiedad" required>
        </div>
        <div class="form-group">
            <label for="ubicacion">Ubicación</label>
            <input type="text" id="ubicacion" name="ubicacion"required>
        </div>
        <div class="form-group">
            <label for="habitaciones">Cantidad de habitaciones</label>
            <input type="number" id="habitaciones" name="habitaciones"required>
        </div>
        <div class="form-group">
            <label for="metros_cuadrados">Metros cuadrados de la propiedad</label>
            <input type="number" id="metros_cuadrados" name="metros_cuadrados" required>
        </div>
        <button type="submit">Agregar</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>