<?php require 'templates/header.phtml' ?>

<div class="login-container">
    <form action="<?= BASE_URL ?>do_login" method="POST" class="login-form">
        <h2 style="color: #d32f2f; font-family: 'Montserrat', Arial, sans-serif; margin-bottom: 18px; text-align: center;">
            Iniciar Sesión
        </h2>

        <?php if (!empty($error)): ?>
            <div class="text-danger"><?= htmlspecialchars($error) ?></div>
        <?php endif; ?>

        <div class="form-group">
            <label for="usuario">Usuario</label>
            <input required name="usuario" id="usuario" type="text" class="form-control" placeholder="Ingrese su usuario">
        </div>

        <div class="form-group">
            <label for="password">Contraseña</label>
            <input required name="password" id="password" type="password" class="form-control" placeholder="Ingrese su contraseña">
        </div>

        <button type="submit">Ingresar</button>
    </form>
</div>

<?php require 'templates/footer.phtml' ?>
