<?php require 'templates/header.phtml' ?>

<h2>Agregar una propiedad </h2>
<form action="<?= BASE_URL ?>agregarPropiedad " method="" class="mt-3">

    <div class="mb-3">
        <label for="id_propietario_fk">Propietario</label>
       <select id="id_propietario_fk" name="id_propietario_fk" class="form-control" required>
        <option value="">Seleccione un propietario</option>
        <?php foreach($propietarios as $propietario): ?>
            <option value="<?= $propietario->id ?>">
                <?= htmlspecialchars($propietario->nombre) ?>
            </option>
        <?php endforeach; ?>
    </select>
    </div>
    <div class="mb-3">
        <label for="tipo_propiedad">Tipo de propiedad</label>
        <input type="text" id="tipo_propiedad" name="tipo_propiedad" class="form-control" required>
    </div>
     <div class="mb-3">
        <label for="ubicacion">Ubicación</label>
        <input type="text" id="ubicacion" name="ubicacion" class="form-control" required>
    </div>
    <div class="mb-3">
        <label for="habitaciones">Cantidad de habitaciones</label>
        <input type="number" id="habitaciones" name="habitaciones" class="form-control" required>
    </div>
    <div class="mb-3">
        <label for="metros_cuadrados">Metros cuadrados de la propiedad</label>
        <input type="number" id="metros_cuadrados" name="metros_cuadrados" class="form-control" required>
    </div>
    
    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>

<?php require 'templates/footer.phtml' ?>