<?php

require 'templates/header.phtml';
?>

<div class="prop-cards-container">
    <?php if (!empty($usuario)): ?>
        <a href="<?= BASE_URL ?>agregarPropiedad/" class="btn-agregar-prop">Agregar Propiedad</a>
    <?php endif; ?>

    <div class="prop-cards-row">
            <div class="prop-card">
             <h5><?= htmlspecialchars($propiedad->tipo_propiedad) ?></h5>
             <div style="margin-bottom: 10px;">
                    <strong>Ubicación:</strong> <?= htmlspecialchars($propiedad->ubicacion) ?><br>
                    <strong>Habitaciones:</strong> <?= htmlspecialchars($propiedad->habitaciones) ?>
                    <strong>Metros cuadrados:</strong> <?= htmlspecialchars($propiedad->metros_cuadrados) ?>
                    <strong>Propietario:</strong> <?= htmlspecialchars($propietario->nombre)  ?><br>
             </div>
                    <a class="btn btn-volver" href="<?= BASE_URL ?>propiedades/">Volver</a>
            </div>
    </div>
</div>

<?php require 'templates/footer.phtml' ?>